/**
 * Theme Configuration for Aha Agile Website
 * 
 * This directory contains CSS themes generated by Loveable AI for the website.
 * Each theme includes complete light and dark mode support with shadcn/ui compatibility.
 * 
 * Available Themes:
 * - Ocean: Blue-based theme with deep ocean tones
 * - Sunset: Warm orange/red theme with cozy sunset colors  
 * - Forest: Green-based theme with natural forest tones
 * 
 * Each theme defines:
 * - Standard shadcn/ui color variables (background, foreground, primary, etc.)
 * - Custom brand tokens (brand-primary, brand-secondary, brand-accent)
 * - Gradient definitions for hero sections
 * - Sidebar component colors
 * - Complete dark mode variants
 * 
 * Usage:
 * Import themes in your Next.js app by adding to globals.css or layout.tsx
 * Apply themes by adding/removing CSS classes or switching stylesheets
 * 
 * Color Format: HSL space-separated values (e.g., "200 100% 25%")
 * Compatible with: Tailwind CSS, shadcn/ui components
 */

export const AVAILABLE_THEMES = [
  {
    name: 'Ocean',
    id: 'ocean',
    description: 'Deep blue ocean tones with excellent contrast',
    file: './ocean.css',
    colors: {
      primary: 'hsl(200 100% 25%)', // Deep ocean blue
      accent: 'hsl(180 100% 35%)',  // Teal accent
      background: 'hsl(200 30% 98%)', // Light blue-gray
    }
  },
  {
    name: 'Sunset',
    id: 'sunset', 
    description: 'Warm sunset colors with cozy orange/red tones',
    file: './sunset.css',
    colors: {
      primary: 'hsl(15 85% 50%)',   // Warm orange
      accent: 'hsl(340 75% 55%)',   // Pink accent
      background: 'hsl(30 40% 98%)', // Warm off-white
    }
  },
  {
    name: 'Forest',
    id: 'forest',
    description: 'Natural green forest theme with earthy tones',
    file: './forest.css', 
    colors: {
      primary: 'hsl(150 80% 25%)',  // Forest green
      accent: 'hsl(65 85% 45%)',    // Lime accent
      background: 'hsl(120 20% 98%)', // Light green-gray
    }
  }
] as const;

export type ThemeId = typeof AVAILABLE_THEMES[number]['id'];